# ProvTranslator interoperability tests
#
# This job assumes the following packages have been installed (these
# are provided by the Travis CI build environment,
# http://docs.travis-ci.com/user/ci-environment:
#
# git
# curl
# python 2.7
# graphviz 

language: python

python:
  - 2.7

addons:
  apt:
    packages:
    - zlib1g-dev
    - libxslt1-dev

before_install:
  - echo "Getting test harness..."
  - git clone https://github.com/mikej888/interop-test-harness
  - cd interop-test-harness
  - git checkout package
  - source scripts/install-prov-interop-comparator.sh
  - python setup.py install
  - cd ..
  - echo "Getting test cases..."
  - git clone https://github.com/prov-suite/testcases

script: 
  - nosetests prov_interop_provtranslator.interop_tests.test_provtranslator > log.txt
