# ProvTranslator interoperability tests
#
# This job assumes the following packages have been installed (these
# are provided by the Travis CI build environment,
# http://docs.travis-ci.com/user/ci-environment:
#
# git
# curl
# python 2.7
# graphviz 

language: python

python:
  - 2.7

env:
  matrix:
    - TEST_RUN="-v prov_interop_provtranslator/tests"
    - TEST_RUN="prov_interop_provtranslator/interop_tests > log.txt"

addons:
  apt:
    packages:
    - zlib1g-dev
    - libxslt1-dev

before_install:
  - echo "Getting test harness..."
  - git clone https://github.com/prov-suite/interop-test-harness
  - cd interop-test-harness
  - git checkout package
  - source scripts/install-prov-interop-comparator.sh
  - pip install -r requirements.txt
  - python setup.py install
  - cd ..
  - echo "Getting test cases..."
  - git clone https://github.com/prov-suite/testcases

install:
  - pip install -r requirements.txt
  
script: 
  - nosetests $TEST_RUN
