# ProvTranslator interoperability tests
#
# This job assumes the following packages have been installed (these
# are provided by the Travis CI build environment,
# http://docs.travis-ci.com/user/ci-environment:
#
# git
# curl
# python 2.7
# graphviz 

language: python

python:
  - 2.7

addons:
  apt:
    packages:
    - zlib1g-dev
    - libxslt1-dev

before_install:
  - echo "Getting test cases..."
  - git clone https://github.com/prov-suite/testcases testcases
  - echo "Getting ProvPy package for use as a comparator..."
  - pip install prov
  - prov-compare --version
  - echo "Getting test harness..."
  - git clone https://github.com/prov-suite/interop-test-harness test-harness
  - cd test-harness
  - pip install -r requirements.txt
  - echo "Creating local configuration..."
  - cp -r config localconfig
  - python prov_interop/set-yaml-value.py localconfig/harness.yaml test-cases="$TRAVIS_BUILD_DIR/testcases"
  - cat localconfig/*

script: 
  - nosetests -v prov_interop.interop_tests.test_provtranslator
